export interface Property {
  id: string
  title: string
  zone: string
  type: 'Venta' | 'Renta'
  category: PropertyCategory
  price: string
  numericPrice: number
  bedrooms: number
  bathrooms: number
  constructionArea: string
  landArea?: string
  description: string
  highlights: string[]
  image: string
  featured?: boolean
}

export type PropertyCategory =
  | 'casas'
  | 'departamentos'
  | 'townhouses'
  | 'naves-industriales'
  | 'locales-comerciales'
  | 'lotes-inversion'
  | 'terrenos'
  | 'oficinas'

export const PROPERTY_CATEGORIES: { value: PropertyCategory; label: string }[] = [
  { value: 'casas', label: 'Casas' },
  { value: 'departamentos', label: 'Departamentos' },
  { value: 'townhouses', label: 'Townhouses' },
  { value: 'naves-industriales', label: 'Naves Industriales' },
  { value: 'locales-comerciales', label: 'Locales Comerciales' },
  { value: 'lotes-inversion', label: 'Lotes de Inversión' },
  { value: 'terrenos', label: 'Terrenos' },
  { value: 'oficinas', label: 'Oficinas' },
]

export const REAL_PROPERTIES: Property[] = [
  {
    id: 'WS005',
    title: 'Departamento en Renta en Pensiones, Mérida, Yucatán',
    zone: 'Pensiones, Mérida',
    type: 'Renta',
    category: 'departamentos',
    price: '7,000 MXN',
    numericPrice: 7000,
    bedrooms: 1,
    bathrooms: 1,
    constructionArea: '50 m²',
    description: 'DEPA ESTUDIO EN RENTA Ubicado en Pensiones, cercano a todos los servicios que requieres como transporte, gasolineras, oxxos, super mercados, restaurantes etc. y vías de acceso fáciles. El estudio se e...',
    highlights: ['AirConditioner', 'EvaporativeCooler', 'Furnished', 'EquippedKitchen'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260606105458-9c0ed5e6a0f6456db524721a72ca1eb1l.webp',
    featured: false
  },
  {
    id: 'WS007',
    title: 'Departamento en Renta en Los Héroes, Mérida, Yucatán',
    zone: 'Los Héroes, Mérida',
    type: 'Renta',
    category: 'departamentos',
    price: '4,500 MXN',
    numericPrice: 4500,
    bedrooms: 1,
    bathrooms: 1,
    constructionArea: '30 m²',
    description: 'DEPARTAMENTO EN RENTA Ubicado en Fracc. Heroes Este departamento amueblado, se encuentra en planta alta, cuenta con: Recámara separada Espacio de comedor Estufa de inducción 4 quemadores Refrigerador ...',
    highlights: ['AirConditioner', 'Furnished', 'Heater', 'EquippedKitchen'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260611110112-6a0c21bff8834b47ba8f0b48c72b2941l.webp',
    featured: false
  },
  {
    id: 'WS009',
    title: 'Departamento en Renta en Los Héroes, Mérida, Yucatán',
    zone: 'Los Héroes, Mérida',
    type: 'Renta',
    category: 'departamentos',
    price: '4,300 MXN',
    numericPrice: 4300,
    bedrooms: 1,
    bathrooms: 1,
    constructionArea: '25 m²',
    description: 'DEPARTAMENTO EN RENTA🏠 📍Ubicado en el Fracc. Héroes Este departamento amueblado, se encuentra en planta alta, cuenta con: Recámara separada Espacio de comedor Estufa de inducción 4 quemadores Refriger...',
    highlights: ['AirConditioner', 'Furnished', 'EquippedKitchen', 'GatedCommunity'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260721123139-00942d86ea6d42cf81bb2803bb78637al.webp',
    featured: false
  },
  {
    id: 'WS010',
    title: 'Casa en Renta en Punta Esmeralda, Mérida, Yucatán',
    zone: 'Punta Esmeralda, Mérida',
    type: 'Renta',
    category: 'casas',
    price: '8,500 MXN',
    numericPrice: 8500,
    bedrooms: 2,
    bathrooms: 2,
    constructionArea: '133 m²',
    landArea: '75 m²',
    description: 'Ubicada en una de las privadas con mayor tranquilidad de Mérida. Esta casa se encuentra dentro de Privada Punta Esmeralda, un desarrollo diseñado para ofrecer seguridad, comodidad y espacios ideales p...',
    highlights: ['AirConditioner', 'Heater', 'Garage', 'IntegralKitchen'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260626171513-e0bd39d3941345e1bda07dc4078a9dd7l.webp',
    featured: false
  },
  {
    id: 'WS028',
    title: 'Departamento en Renta en Chicxulub Puerto, Progreso, Yucatán',
    zone: 'Chicxulub Puerto, Mérida',
    type: 'Renta',
    category: 'departamentos',
    price: '1,500 MXN',
    numericPrice: 1500,
    bedrooms: 1,
    bathrooms: 1,
    constructionArea: '65 m²',
    description: 'Departamento Vacacional en Chicxulub, Yucatán, CALLE 23-A. Disfruta de la tranquilidad de la costa yucateca en un departamento totalmente equipado, ideal para escaparte unos días junto al mar. 1 habit...',
    highlights: ['AirConditioner', 'Furnished', 'Heater', 'CCTV'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260626185834-d0b3073e0fad4804af573e5db2df2963l.webp',
    featured: false
  },
  {
    id: 'WS036',
    title: 'Casa en Venta en Dzitya, Mérida, Yucatán',
    zone: 'Dzitya, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '3,100,000 MXN',
    numericPrice: 3100000,
    bedrooms: 2,
    bathrooms: 4,
    constructionArea: '182.44 m²',
    landArea: '75.6 m²',
    description: 'Dzityá, una tierra de herencia maya y tradición artesanal, es el escenario perfecto para Villas del Conde, un conjunto residencial diseñado para quienes buscan exclusividad, confort y conexión con la ...',
    highlights: ['Internet', 'Telephone', 'SeniorAccessibility', 'DisabledAccess'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260721183232-720d99a710f441c2959a51ae4003fdd9l.webp',
    featured: false
  },
  {
    id: 'WS037',
    title: 'Terreno en Venta en Tixcuytun, Mérida, Yucatán',
    zone: 'Tixcuytun, Mérida',
    type: 'Venta',
    category: 'terrenos',
    price: '1,100,000 MXN',
    numericPrice: 1100000,
    bedrooms: 0,
    bathrooms: 0,
    constructionArea: '0 m²',
    landArea: '358 m²',
    description: 'Excelente terreno en venta ubicado en privada residencial Entreparques, El proyecto se encuentra ubicado al norte de la ciudad de Mérida en la zona de Tixcuytún, a corta distancia de las principales z...',
    highlights: ['PetsAllowed'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722103715-6c389c9243fc4309b004cffe2fc8efeel.webp',
    featured: false
  },
  {
    id: 'WS038',
    title: 'Casa en Venta en Conkal, Conkal, Yucatán',
    zone: 'Conkal, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '4,380,000 MXN',
    numericPrice: 4380000,
    bedrooms: 3,
    bathrooms: 4,
    constructionArea: '270 m²',
    landArea: '300 m²',
    description: 'Modelo Premium Kanan 270m2 de construcción Entrega en 6 meses, 15% de enganche y plan de pagos de acuerdo a la entrega. Incluye: -1 recamara c/vestidor/baño en P.B. -1 recamaras c/closet/baño en P.A. ...',
    highlights: [],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722104412-c78a63ffe21949b8ac01a8f7df4f9258l.webp',
    featured: false
  },
  {
    id: 'WS039',
    title: 'Terreno en Venta en Conkal, Conkal, Yucatán',
    zone: 'Conkal, Mérida',
    type: 'Venta',
    category: 'terrenos',
    price: '700,000 MXN',
    numericPrice: 700000,
    bedrooms: 0,
    bathrooms: 0,
    constructionArea: '0 m²',
    landArea: '318 m²',
    description: 'Terreno en Residencial Kanan, ubicado en Conkal, Yucatán, una de las zonas con mayor crecimiento y plusvalía en el estado. Características: • Medidas: 12 m de frente x 26.50 m de fondo • Superficie to...',
    highlights: ['Vigilance'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722110144-ff3f1cddc8194bebaa6fa2b4d136c7cdl.webp',
    featured: false
  },
  {
    id: 'WS040',
    title: 'Casa en Renta en Francisco de Montejo II, Mérida, Yucatán',
    zone: 'Francisco de Montejo II, Mérida',
    type: 'Renta',
    category: 'casas',
    price: '16,000 MXN',
    numericPrice: 16000,
    bedrooms: 4,
    bathrooms: 3,
    constructionArea: '170 m²',
    landArea: '164 m²',
    description: 'Casa en renta en Francisco de Montejo Una de las Zonas con mayor conectividad de Mérida. Parques cercanos, super mercados como Bodega Aurrera, transporte, escuelas y comercios, todos los servicios cer...',
    highlights: ['SeniorAccessibility', 'AirConditioner', 'Balcony', 'Garage'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260730173557-9b940025731d4f05937eca62755f5b7al.webp',
    featured: false
  },
  {
    id: 'WS041',
    title: 'Terreno en Venta en Altabrisa, Mérida, Yucatán',
    zone: 'Altabrisa, Mérida',
    type: 'Venta',
    category: 'terrenos',
    price: '6,700,000 MXN',
    numericPrice: 6700000,
    bedrooms: 0,
    bathrooms: 0,
    constructionArea: '0 m²',
    landArea: '554.75 m²',
    description: 'Este terreno en esquina, con una superficie de 554.75 m2, te ofrece la oportunidad de crear, desarrollar y proyectar en una ubicación estratégica y privilegiada. Ubicado en la codiciada colonia Altabr...',
    highlights: [],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722111315-f1170c61ee03454384c241e589be12cfl.webp',
    featured: false
  },
  {
    id: 'WS042',
    title: 'Casa en Venta en Dzitya, Mérida, Yucatán',
    zone: 'Dzitya, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '2,190,000 MXN',
    numericPrice: 2190000,
    bedrooms: 2,
    bathrooms: 2,
    constructionArea: '90 m²',
    landArea: '160 m²',
    description: 'Residencia de 2 plantas con amplio jardín Superficie construida total: 90.06 m2 (Planta baja 45.03 m2 + Planta alta 45.03 m2) El Modelo Tulum II combina arquitectura moderna, iluminación natural y esp...',
    highlights: ['AirConditioner', 'PetsAllowed', 'Patio'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722115509-b14cf4a931cc49b1bf6eb77492dbe872l.webp',
    featured: false
  },
  {
    id: 'WS043',
    title: 'Casa en Venta en Dzitya, Mérida, Yucatán',
    zone: 'Dzitya, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '2,331,271 MXN',
    numericPrice: 2331271,
    bedrooms: 2,
    bathrooms: 2,
    constructionArea: '108.22 m²',
    landArea: '200 m²',
    description: 'Terreno de 10.00x20 (200 m2) medidas varían según la calle de ubicación. -Zona de alta seguridad con rápido desarrollo y plusvalía. -Con acceso directo a periférico y carretera a progreso y para facil...',
    highlights: [],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722121028-11c3b380051f47de9c93d98054a3fb73l.webp',
    featured: false
  },
  {
    id: 'WS044',
    title: 'Casa en Venta en Dzitya, Mérida, Yucatán',
    zone: 'Dzitya, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '2,717,187 MXN',
    numericPrice: 2717187,
    bedrooms: 3,
    bathrooms: 3,
    constructionArea: '126.81 m²',
    landArea: '175.74 m²',
    description: 'Modelo Palenque Residencial en Dzitya, Mérida – Yucatán Dos niveles · 3 recámaras · 2 baños completos Ubicación estratégica. • Conexión inmediata a Periférico y carretera a Progreso: movilidad ágil si...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'AirConditioner', 'Furnished'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722122223-2248c7ed885648279ee54556403b4e43l.webp',
    featured: false
  },
  {
    id: 'WS045',
    title: 'Terreno en Venta en Conkal, Conkal, Yucatán',
    zone: 'Conkal, Mérida',
    type: 'Venta',
    category: 'terrenos',
    price: '870,000 MXN',
    numericPrice: 870000,
    bedrooms: 0,
    bathrooms: 0,
    constructionArea: '0 m²',
    landArea: '542.73 m²',
    description: 'Se encuentra a la venta un predio de 542.73 metros cuadrados en la calle de S/C, en la colonia Conkal, un área con uso de suelo mixto que permite una variedad de desarrollos comerciales y residenciale...',
    highlights: ['PetsAllowed', 'SmokingAllowed'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722184452-3d54820c969a44dba8153500b19f7030l.webp',
    featured: false
  },
  {
    id: 'WS046',
    title: 'Casa en Venta en Pensiones, Mérida, Yucatán',
    zone: 'Pensiones, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '3,400,000 MXN',
    numericPrice: 3400000,
    bedrooms: 4,
    bathrooms: 3,
    constructionArea: '288.44 m²',
    landArea: '173.5 m²',
    description: 'Esta propiedad de 288.44 m2 de construcción en un terreno de 173.50 m2 ofrece una distribución ideal para quienes buscan espacio y funcionalidad en una ubicación céntrica de Mérida: Características: •...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'AirConditioner', 'Furnished'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260722185809-cc875f1103164852be37733b3038fec6l.webp',
    featured: false
  },
  {
    id: 'WS047',
    title: 'Casa en Venta en Conkal, Conkal, Yucatán',
    zone: 'Conkal, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '3,750,000 MXN',
    numericPrice: 3750000,
    bedrooms: 3,
    bathrooms: 3,
    constructionArea: '240 m²',
    landArea: '300 m²',
    description: 'Residencia Nueva en Praderas del Mayab Descubre esta espectacular residencia ubicada en **Praderas del Mayab**, una exclusiva privada residencial al norte de Mérida, sobre la carretera Mérida–Chicxulu...',
    highlights: ['GameArea', 'ClosedAreaMall', 'Terrace', 'WaterView'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260727110258-47eb46c902a840859b815fe04f169138l.webp',
    featured: false
  },
  {
    id: 'WS049',
    title: 'Casa en Venta en Dzitya, Mérida, Yucatán',
    zone: 'Dzitya, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '4,075,000 MXN',
    numericPrice: 4075000,
    bedrooms: 3,
    bathrooms: 3,
    constructionArea: '216 m²',
    landArea: '240 m²',
    description: 'Residencia de diseño moderno con amplios espacios y excelente distribución,Lista para entrega. Casa de dos niveles ubicada en un terreno de 12 x 20 m, diseñada para brindar comodidad, iluminación natu...',
    highlights: ['GameArea', 'Garden', 'Terrace', 'Library'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260723115551-d01ab1c897924b479e25e1997b05de57l.webp',
    featured: false
  },
  {
    id: 'WS050',
    title: 'Casa en Venta en Montes de Ame, Mérida, Yucatán',
    zone: 'Montes de Ame, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '7,500,000 MXN',
    numericPrice: 7500000,
    bedrooms: 4,
    bathrooms: 4,
    constructionArea: '490 m²',
    landArea: '720 m²',
    description: 'Imagina despertar cada mañana en una de las zonas más exclusivas y tranquilas de Mérida, Yucatán, al norte de la ciudad, rodeado de comodidad, estilo y amplitud, estarás cerca de universidades, hospit...',
    highlights: ['AirConditioner', 'Grill', 'Balcony', 'Garage'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260723104853-77a4757631bd43c69e559d9f128826d0l.webp',
    featured: false
  },
  {
    id: 'WS051',
    title: 'Casa en Venta en Cholul, Mérida, Yucatán',
    zone: 'Cholul, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '4,509,000 MXN',
    numericPrice: 4509000,
    bedrooms: 4,
    bathrooms: 6,
    constructionArea: '289.22 m²',
    landArea: '300 m²',
    description: 'Descripción: San Pedro Cholul a solo 2.9 kms. del Periférico y muy cerca de la salida a Motul. Descubre un desarrollo exclusivo al norte de Mérida, dentro de una privada residencial privada con: Casa ...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'AirConditioner', 'Grill'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260727181415-a74d2910ebbe4f1b8ae64fd86818e2dal.webp',
    featured: false
  },
  {
    id: 'WS052',
    title: 'Casa en Venta en Temozon Norte, Mérida, Yucatán',
    zone: 'Temozon Norte, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '6,200,000 MXN',
    numericPrice: 6200000,
    bedrooms: 3,
    bathrooms: 4,
    constructionArea: '249.5 m²',
    landArea: '289.78 m²',
    description: 'A 1 km de Plaza la Isla y Cabo Norte, Cerca de los Colegios Teresiano y Cuam Ceam, Universidad Marista y UVM. Seguridad privada con caseta de control de acceso a la privada y caseta adicional en cada ...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'AirConditioner', 'EvaporativeCooler'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260727201329-bd7996b1d27b4d2bbc9ca19db3e3d81dl.webp',
    featured: false
  },
  {
    id: 'WS053',
    title: 'Departamento en Venta en Cholul, Mérida, Yucatán',
    zone: 'Cholul, Mérida',
    type: 'Venta',
    category: 'departamentos',
    price: '2,970,000 MXN',
    numericPrice: 2970000,
    bedrooms: 1,
    bathrooms: 2,
    constructionArea: '77 m²',
    description: 'EN PASEO NORTE, MERIDA, CHOLUL – CABO NORTE. -DEPARTAMENTOS TOTALMENTE AMUEBLADOS. -EDIFICIO DE 4 NIVELES Y ROOF TOP -ENGANCHE 10%. -SALDO 90% CONTRA ENTREGA DICIEMBRE 2026. -MODELO ALTON 1 RECAMARA 7...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'AirConditioner', 'Furnished'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260727213250-6fa87b1c067647c18462af6b2a0c3ec8l.webp',
    featured: false
  },
  {
    id: 'WS054',
    title: 'Casa en Venta en Temozon Norte, Mérida, Yucatán',
    zone: 'Temozon Norte, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '6,800,000 MXN',
    numericPrice: 6800000,
    bedrooms: 3,
    bathrooms: 5,
    constructionArea: '278 m²',
    landArea: '300 m²',
    description: 'Residencia en Privada, en Temozón Norte (Preventa) A 1 km de Plaza la Isla y Cabo Norte, Cerca de los Colegios Teresiano y Cuam Ceam, Universidad Marista y UVM. Seguridad privada con caseta de control...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'AirConditioner', 'Balcony'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260727214917-ab081e2730954bd7813dd156e3561a6bl.webp',
    featured: false
  },
  {
    id: 'WS055',
    title: 'Casa en Venta en Xcanatún, Mérida, Yucatán',
    zone: 'Xcanatún, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '4,600,000 MXN',
    numericPrice: 4600000,
    bedrooms: 4,
    bathrooms: 4,
    constructionArea: '183 m²',
    landArea: '300 m²',
    description: 'Equpamiento - Granito en cocina - Pisos de gran dormato - Muebles bajo lavabo - Canceles de baño - Calentador electrico - Presurizador de agua - Gabinetes inferiores y superiores - Islas en cocina -Cl...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'Garage', 'IntegralKitchen'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260728125813-6ce2f0f7106c4263943e805a1b5f8684l.webp',
    featured: false
  },
  {
    id: 'WS056',
    title: 'Casa en Venta en Xcanatún, Mérida, Yucatán',
    zone: 'Xcanatún, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '4,800,000 MXN',
    numericPrice: 4800000,
    bedrooms: 4,
    bathrooms: 5,
    constructionArea: '226 m²',
    landArea: '300 m²',
    description: 'Equpamiento - Granito en cocina - Pisos de gran dormato - Muebles bajo lavabo - Canceles de baño - Calentador electrico - Presurizador de agua - Gabinetes inferiores y superiores - Islas en cocina -Cl...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'Grill', 'CCTV'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260728125434-4ce47936f9ed404b9ed794a67fe46fecl.webp',
    featured: false
  },
  {
    id: 'WS057',
    title: 'Casa en Venta en Xcanatún, Mérida, Yucatán',
    zone: 'Xcanatún, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '5,100,000 MXN',
    numericPrice: 5100000,
    bedrooms: 4,
    bathrooms: 5,
    constructionArea: '226 m²',
    landArea: '300 m²',
    description: 'Equpamiento - Granito en cocina - Pisos de gran dormato - Muebles bajo lavabo - Canceles de baño - Calentador electrico - Presurizador de agua - Gabinetes inferiores y superiores - Islas en cocina -Cl...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'CCTV', 'Cistern'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260728130849-732c9e4c888c4439b37d5c34cfa8e9afl.webp',
    featured: false
  },
  {
    id: 'WS058',
    title: 'Casa en Venta en Xcanatún, Mérida, Yucatán',
    zone: 'Xcanatún, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '5,250,000 MXN',
    numericPrice: 5250000,
    bedrooms: 4,
    bathrooms: 5,
    constructionArea: '233 m²',
    landArea: '300 m²',
    description: 'Equpamiento - Granito en cocina - Pisos de gran dormato - Muebles bajo lavabo - Canceles de baño - Calentador electrico - Presurizador de agua - Gabinetes inferiores y superiores - Islas en cocina -Cl...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'EvaporativeCooler', 'CCTV'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260728131640-12e14b0d2e264671b62647973f257f4cl.webp',
    featured: false
  },
  {
    id: 'WS059',
    title: 'Departamento en Venta en Montes de Ame, Mérida, Yucatán',
    zone: 'Montes de Ame, Mérida',
    type: 'Venta',
    category: 'departamentos',
    price: '2,690,000 MXN',
    numericPrice: 2690000,
    bedrooms: 2,
    bathrooms: 2,
    constructionArea: '98 m²',
    description: 'Amplio y funcional departamento en una de las zonas con mayor plusvalía del norte de Mérida, con excelente conectividad al periférico y a pocos minutos de Plaza San Ángelo y Plaza Altabrisa. Distribuc...',
    highlights: ['SeniorAccessibility', 'DisabledAccess', 'AirConditioner', 'Furnished'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260729092029-f3b59ee613e24856aa787a0a330f07fal.webp',
    featured: false
  },
  {
    id: 'WS060',
    title: 'Departamento en Renta en Merida Centro, Mérida, Yucatán',
    zone: 'Merida Centro, Mérida',
    type: 'Renta',
    category: 'departamentos',
    price: '7,500 MXN',
    numericPrice: 7500,
    bedrooms: 1,
    bathrooms: 1,
    constructionArea: '72 m²',
    description: 'Excelente ubicación, en el Centro de Mérida, a una cuadra de la Av. Itzaes y muy cerca de la Clínica de Mérida y el Hospital O’Horán. Una opción práctica para quienes buscan vivir cerca de hospitales,...',
    highlights: ['SeniorAccessibility', 'AirConditioner', 'Furnished', 'EquippedKitchen'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260730185639-9b6d64d55fef40e093367e28a0f38908l.webp',
    featured: false
  },
  {
    id: 'WS068',
    title: 'Terreno en Renta en Azcorra, Mérida, Yucatán',
    zone: 'Azcorra, Mérida',
    type: 'Renta',
    category: 'terrenos',
    price: '20,000 MXN',
    numericPrice: 20000,
    bedrooms: 0,
    bathrooms: 0,
    constructionArea: '0 m²',
    landArea: '400 m²',
    description: 'Terreno en Renta Ubicado en la Colonia Azcorra A pocos pasos de escuelas y frente a parque , lo que lo hace ideal para negocios o proyectos que busquen alto flujo de personas. Cercano a comercios y se...',
    highlights: [],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260812164117-98f12948dece4e82bd755da9298a9ab3l.webp',
    featured: false
  },
  {
    id: 'WS070',
    title: 'Casa en Renta en Francisco de Montejo, Mérida, Yucatán',
    zone: 'Francisco de Montejo, Mérida',
    type: 'Renta',
    category: 'casas',
    price: '9,000 MXN',
    numericPrice: 9000,
    bedrooms: 2,
    bathrooms: 1,
    constructionArea: '162 m²',
    landArea: '73 m²',
    description: 'Casa en renta en Francisco de Montejo Excelente ubicación, a unas cuadras de un parque y cerca de supermercados, tiendas y transporte público. Características: * $9,000 mensuales * 2 recámaras * 1 bañ...',
    highlights: ['NoPetsAllowed', 'StorageRoom', 'Patio', 'EvaporativeCooler'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260816110616-588c7a2c07f5422dab063d2f59950186l.webp',
    featured: false
  },
  {
    id: 'WS071',
    title: 'Departamento en Renta en Residencial Pensiones I y II, Mérida, Yucatán',
    zone: 'Residencial Pensiones I y II, Mérida',
    type: 'Renta',
    category: 'departamentos',
    price: '8,000 MXN',
    numericPrice: 8000,
    bedrooms: 1,
    bathrooms: 1,
    constructionArea: '50 m²',
    description: 'DEPA ESTUDIO EN RENTA Ubicado en Pensiones, cercano a todos los servicios que requieres como transporte, gasolineras, oxxos, super mercados, restaurantes etc. y vías de acceso fáciles. El estudio se e...',
    highlights: ['AirConditioner', 'EvaporativeCooler', 'Furnished', 'EquippedKitchen'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260822125246-6801652d8df04a4a9d6f717b3aa565afl.webp',
    featured: false
  },
  {
    id: 'WS072',
    title: 'Casa en Venta en Jesus Carranza, Mérida, Yucatán',
    zone: 'Jesus Carranza, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '8,500,000 MXN',
    numericPrice: 8500000,
    bedrooms: 4,
    bathrooms: 2,
    constructionArea: '447 m²',
    landArea: '1328 m²',
    description: 'CASA EN VENTA Colonia Jesús Carranza, Mérida, Yuc. Te invitamos a conocerla, ubicada en una de las zonas más emblemáticas de la ciudad de Mérida, donde sus calles están llenas de tradición. Ya sea que...',
    highlights: ['SeniorAccessibility', 'Garage', 'CoveredParking', 'PetsAllowed'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260827170038-c65eb9922f364948a6667943451ef8b7l.webp',
    featured: false
  },
  {
    id: 'WS073',
    title: 'Casa en Venta en Temozon Norte, Mérida, Yucatán',
    zone: 'Temozon Norte, Mérida',
    type: 'Venta',
    category: 'casas',
    price: '4,295,000 MXN',
    numericPrice: 4295000,
    bedrooms: 3,
    bathrooms: 4,
    constructionArea: '263.89 m²',
    landArea: '130 m²',
    description: 'Descubre un proyecto diseñado para quienes buscan lujo, comodidad y plusvalía en la zona más demandada de Mérida. Distribución en tres niveles: • Primer nivel: jardín, sala, comedor, cocina, alberca y...',
    highlights: ['SeniorAccessibility', 'AirConditioner', 'Furnished', 'Grill'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260902121233-c1df2ed30d9244848ec0643b0c354aa5l.webp',
    featured: false
  },
  {
    id: 'WS074',
    title: 'Casa en Renta en Caucel, Mérida, Yucatán',
    zone: 'Caucel, Mérida',
    type: 'Renta',
    category: 'casas',
    price: '7,700 MXN',
    numericPrice: 7700,
    bedrooms: 2,
    bathrooms: 1,
    constructionArea: '75 m²',
    landArea: '200 m²',
    description: 'Ubicada en Fraccionamiento CAUCEL, Mérida, Yucatán. Se ubica muy cerca de la UPY, con varias vías de acceso y cerca de anillo periférico lo que hace que su acceso sea inmediato , de igual manera podrá...',
    highlights: ['AirConditioner', 'EvaporativeCooler', 'GatedCommunity', 'NoPetsAllowed'],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260908132206-0c299b5f00164cf0ba82d7ca26ae6e0al.webp',
    featured: false
  },
  {
    id: 'WS029',
    title: 'Departamento en Renta en Chicxulub Puerto',
    zone: 'Chicxulub Puerto, Progreso, Yucatán',
    type: 'Renta',
    category: 'departamentos',
    price: '8,500 MXN',
    numericPrice: 8500,
    bedrooms: 1,
    bathrooms: 1,
    constructionArea: '50 m²',
    description: 'Departamento en renta en Chicxulub Puerto, Progreso, Yucatán. 1 habitación, 1 baño completo, 50 m² de construcción.',
    highlights: [],
    image: 'https://s3.amazonaws.com/nocnok-img/pp-260721124326-ecc9a3d2fb78484bb6d17c5680139c5bl.webp',
    featured: false
  },
]
